name: VI
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.2=pyhc872135_1
  - python=3.9.24=h716150d_1
  - setuptools=80.9.0=py39haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py39haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - asttokens==3.0.0
      - bottleneck==1.5.0
      - catboost==1.2.8
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fonttools==4.60.1
      - graphviz==0.21
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - intel-cmplr-lib-ur==2025.3.0
      - intel-openmp==2025.3.0
      - ipykernel==6.31.0
      - ipython==8.18.1
      - jedi==0.19.2
      - joblib==1.5.2
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.7
      - lightgbm==4.6.0
      - matplotlib==3.9.4
      - matplotlib-inline==0.2.1
      - mkl==2025.3.0
      - mkl-fft==2.1.1
      - mkl-random==1.3.0
      - mkl-service==2.4.0
      - narwhals==2.10.0
      - nest-asyncio==1.6.0
      - numexpr==2.10.2
      - numpy==2.0.2
      - onemkl-license==2025.3.0
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pickleshare==0.7.5
      - pillow==11.3.0
      - platformdirs==4.4.0
      - plotly==6.3.1
      - prompt-toolkit==3.0.52
      - psutil==7.1.2
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywin32==311
      - pyzmq==27.1.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - six==1.17.0
      - stack-data==0.6.3
      - tbb==2022.3.0
      - tcmlib==1.4.1
      - threadpoolctl==3.6.0
      - tornado==6.5.2
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - umf==1.0.2
      - wcwidth==0.2.14
      - xgboost==2.1.4
      - zipp==3.23.0
prefix: C:\Users\omerg\miniconda3\envs\VI
